version: '3.9'

services:
  frontend: 
    build: 
      context: ./library-management-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    restart: always
    volumes:
      - ./library-management-frontend:/app
  
  backend: 
    build: 
      context: ./library-management-backend
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    working_dir: /app
    restart: "always"
    depends_on: 
      - database
    volumes:
      - ./library-management-backend:/app
    environment:
      DEV_DB_HOST: database
  
  database: 
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb:/data/db/
volumes: 
  mongodb: