name: node-helloworld

on:
  push: 
    branches: [main]

jobs:
  docker: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} 

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      
      - name: Build and Push Docker image for backend
        uses: docker/build-push-action@v2
        id: docker_build_back
        with: 
          context: ./library-management-backend
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lib-management-backend
      - name: Build and Push Docker image for frontend
        uses: docker/build-push-action@v2
        id: docker_build_front
        with: 
          context: ./library-management-frontend
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lib-management-frontend

      - name: Verify
        run: echo ${{ steps.docker_build_back.outputs.digest }}
      - name: Verify
        run: echo ${{ steps.docker_build_front.outputs.digest }}