name: node-helloworld

on:
  push: 
    branches: [main]

jobs:
  docker: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} 

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      
      - name: Build and Push Docker image for backend
        uses: docker/build-push-action@v2
        id: docker_build_back
        with: 
          context: ./library-management-backend
          file: ./library-management-backend/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lib-management-backend
      - name: Build and Push Docker image for frontend
        uses: docker/build-push-action@v2
        id: docker_build_front
        with: 
          context: ./library-management-frontend
          file: ./library-management-frontend/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lib-management-frontend

      - name: Verify
        run: echo ${{ steps.docker_build_back.outputs.digest }}
      - name: Verify
        run: echo ${{ steps.docker_build_front.outputs.digest }}

  deploy-to-gke:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/85976304942/locations/global/workloadIdentityPools/k8s-workload-provider/providers/oidc-provider'
          service_account: 'k8s-service-account@testproject-319403.iam.gserviceaccount.com'

